## Date Processing

In [17]:
import pandas as pd
import re

### Clean Wine Data

In [18]:
df = pd.read_csv("asset/wines.csv")
df

,name,year,wine ID,rating,price,winery,ratings_count,region,number_of_flavors,flavors,number_of_grapes,grapes
0,Brut Premier Champagne N.V.,N.V.,74298,4.2,65.098163,Louis Roederer,52143,Champagne Premier Cru,13,"[{'group': 'tree_fruit', 'stats': {'count': 21...",3,"['Chardonnay', 'Pinot Noir', 'Pinot Meunier']"
1,Oeil de Perdrix Brut Rosé Champagne N.V.,N.V.,1998957,3.9,80.132381,Champagne Devaux,856,Champagne,12,"[{'group': 'red_fruit', 'stats': {'count': 86,...",3,"['Chardonnay', 'Pinot Noir', 'Pinot Meunier']"
2,Grand Brut Champagne N.V.,N.V.,79160,4.2,67.333250,Perrier-Jouët,39646,Champagne,13,"[{'group': 'tree_fruit', 'stats': {'count': 17...",3,"['Chardonnay', 'Pinot Noir', 'Pinot Meunier']"
3,Brut Cuvée Champagne Rosé N.V.,N.V.,8305,4.4,69.057174,Laurent-Perrier,35543,Champagne,13,"[{'group': 'red_fruit', 'stats': {'count': 147...",3,"['Chardonnay', 'Pinot Noir', 'Pinot Meunier']"
4,Brut Rosé Champagne N.V.,N.V.,1211816,4.4,57.029800,Billecart-Salmon,21474,Champagne,13,"[{'group': 'red_fruit', 'stats': {'count': 131...",3,"['Chardonnay', 'Pinot Noir', 'Pinot Meunier']"
...,...,...,...,...,...,...,...,...,...,...,...,...
964,Barbaresco 2018,2018,61144,4.1,66.194090,Prunotto,1421,Barbaresco,13,"[{'group': 'red_fruit', 'stats': {'count': 574...",1,['Nebbiolo']
965,Max's Shiraz 2016,2016,4275488,3.9,85.807154,Penfolds,1093,South Australia,13,"[{'group': 'oak', 'stats': {'count': 404, 'sco...",1,['Shiraz/Syrah']
966,Vieilles Vignes Gevrey-Chambertin 2012,2012,1189367,4.0,105.860000,Domaine Rossignol-Trapet,326,Gevrey-Chambertin,12,"[{'group': 'red_fruit', 'stats': {'count': 174...",1,['Pinot Noir']
967,Pomerol 2011,2011,1112303,4.1,108.400000,Château Vray Croix de Gay,154,Pomerol,12,"[{'group': 'oak', 'stats': {'count': 107, 'sco...",6,"['Cabernet Sauvignon', 'Cabernet Franc', 'Malb..."
968,Vosne-Romanée 2017,2017,1208798,4.3,91.500000,Albert Bichot,48,Vosne-Romanée,11,"[{'group': 'red_fruit', 'stats': {'count': 28,...",1,['Pinot Noir']

In [19]:
df['flavors'] = df['flavors'].apply(lambda x: dict(zip(re.findall('\'group\W*(.*?)\W', x), re.findall('stats\W*\'count\W*(.*?)\W', x))))
df

,name,year,wine ID,rating,price,winery,ratings_count,region,number_of_flavors,flavors,number_of_grapes,grapes
0,Brut Premier Champagne N.V.,N.V.,74298,4.2,65.098163,Louis Roederer,52143,Champagne Premier Cru,13,"{'tree_fruit': '2161', 'non_oak': '1909', 'cit...",3,"['Chardonnay', 'Pinot Noir', 'Pinot Meunier']"
1,Oeil de Perdrix Brut Rosé Champagne N.V.,N.V.,1998957,3.9,80.132381,Champagne Devaux,856,Champagne,12,"{'red_fruit': '86', 'microbio': '25', 'non_oak...",3,"['Chardonnay', 'Pinot Noir', 'Pinot Meunier']"
2,Grand Brut Champagne N.V.,N.V.,79160,4.2,67.333250,Perrier-Jouët,39646,Champagne,13,"{'tree_fruit': '1741', 'citrus_fruit': '1461',...",3,"['Chardonnay', 'Pinot Noir', 'Pinot Meunier']"
3,Brut Cuvée Champagne Rosé N.V.,N.V.,8305,4.4,69.057174,Laurent-Perrier,35543,Champagne,13,"{'red_fruit': '1476', 'microbio': '715', 'non_...",3,"['Chardonnay', 'Pinot Noir', 'Pinot Meunier']"
4,Brut Rosé Champagne N.V.,N.V.,1211816,4.4,57.029800,Billecart-Salmon,21474,Champagne,13,"{'red_fruit': '1315', 'citrus_fruit': '761', '...",3,"['Chardonnay', 'Pinot Noir', 'Pinot Meunier']"
...,...,...,...,...,...,...,...,...,...,...,...,...
964,Barbaresco 2018,2018,61144,4.1,66.194090,Prunotto,1421,Barbaresco,13,"{'red_fruit': '574', 'oak': '393', 'earth': '3...",1,['Nebbiolo']
965,Max's Shiraz 2016,2016,4275488,3.9,85.807154,Penfolds,1093,South Australia,13,"{'oak': '404', 'black_fruit': '360', 'spices':...",1,['Shiraz/Syrah']
966,Vieilles Vignes Gevrey-Chambertin 2012,2012,1189367,4.0,105.860000,Domaine Rossignol-Trapet,326,Gevrey-Chambertin,12,"{'red_fruit': '174', 'earth': '134', 'oak': '1...",1,['Pinot Noir']
967,Pomerol 2011,2011,1112303,4.1,108.400000,Château Vray Croix de Gay,154,Pomerol,12,"{'oak': '107', 'earth': '95', 'black_fruit': '...",6,"['Cabernet Sauvignon', 'Cabernet Franc', 'Malb..."
968,Vosne-Romanée 2017,2017,1208798,4.3,91.500000,Albert Bichot,48,Vosne-Romanée,11,"{'red_fruit': '28', 'earth': '20', 'oak': '16'...",1,['Pinot Noir']

### Clean Review Data

In [20]:
df2 = pd.read_pickle("asset/reviews.pkl")
df2

,wine ID,User Rating,Review,CreatedAt,country,name,year,rating,price,winery,ratings_count,region,number_of_flavors,flavors,number_of_grapes,grapes
0,74298,4.5,Beautifully complex champagne. Begins with a y...,2015-07-13T22:05:13.000Z,France,Brut Premier Champagne N.V.,N.V.,4.2,65.098163,Louis Roederer,52143,Champagne Premier Cru,13,"[{'group': 'tree_fruit', 'stats': {'count': 21...",3,"['Chardonnay', 'Pinot Noir', 'Pinot Meunier']"
1,74298,4.5,"Its a Non Vintage, but drinking old as cellare...",2021-06-19T03:38:24.000Z,France,Brut Premier Champagne N.V.,N.V.,4.2,65.098163,Louis Roederer,52143,Champagne Premier Cru,13,"[{'group': 'tree_fruit', 'stats': {'count': 21...",3,"['Chardonnay', 'Pinot Noir', 'Pinot Meunier']"
2,74298,4.5,"In between the Italian wine reviews, it was ti...",2016-10-20T18:45:18.000Z,France,Brut Premier Champagne N.V.,N.V.,4.2,65.098163,Louis Roederer,52143,Champagne Premier Cru,13,"[{'group': 'tree_fruit', 'stats': {'count': 21...",3,"['Chardonnay', 'Pinot Noir', 'Pinot Meunier']"
3,74298,4.5,"Ripe open toasty, powerfull, Smells less compl...",2017-06-06T10:03:49.000Z,France,Brut Premier Champagne N.V.,N.V.,4.2,65.098163,Louis Roederer,52143,Champagne Premier Cru,13,"[{'group': 'tree_fruit', 'stats': {'count': 21...",3,"['Chardonnay', 'Pinot Noir', 'Pinot Meunier']"
4,74298,4.5,This is a lovely NV Champagne at this price le...,2018-03-18T13:43:44.000Z,France,Brut Premier Champagne N.V.,N.V.,4.2,65.098163,Louis Roederer,52143,Champagne Premier Cru,13,"[{'group': 'tree_fruit', 'stats': {'count': 21...",3,"['Chardonnay', 'Pinot Noir', 'Pinot Meunier']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351761,1208798,3.0,"Dry, slight oak. Crisp. Great French chard for...",2016-10-19T21:05:57.000Z,France,Vosne-Romanée 2017,2017,4.3,91.500000,Albert Bichot,48,Vosne-Romanée,11,"[{'group': 'red_fruit', 'stats': {'count': 28,...",1,['Pinot Noir']
351762,1208798,4.0,"Superb, with a long life ahead of it. Well, no...",2014-08-18T16:33:43.000Z,France,Vosne-Romanée 2017,2017,4.3,91.500000,Albert Bichot,48,Vosne-Romanée,11,"[{'group': 'red_fruit', 'stats': {'count': 28,...",1,['Pinot Noir']
351763,1208798,4.5,A bit heavy but very good after 6y,2020-10-09T18:42:04.000Z,France,Vosne-Romanée 2017,2017,4.3,91.500000,Albert Bichot,48,Vosne-Romanée,11,"[{'group': 'red_fruit', 'stats': {'count': 28,...",1,['Pinot Noir']
351764,1208798,5.0,"Very fruity, Elegant, expressive and Hint of O...",2020-03-19T19:13:30.000Z,France,Vosne-Romanée 2017,2017,4.3,91.500000,Albert Bichot,48,Vosne-Romanée,11,"[{'group': 'red_fruit', 'stats': {'count': 28,...",1,['Pinot Noir']
351765,1208798,4.5,"Lighter, very well balanced, taste of terroir-...",2016-04-11T11:01:18.000Z,France,Vosne-Romanée 2017,2017,4.3,91.500000,Albert Bichot,48,Vosne-Romanée,11,"[{'group': 'red_fruit', 'stats': {'count': 28,...",1,['Pinot Noir']

In [21]:
df2.drop('flavors', axis=1, inplace=True)
df2 = df2.merge(df[['wine ID', 'year', 'flavors']], how='left', on=['wine ID', 'year'])
df2

,wine ID,User Rating,Review,CreatedAt,country,name,year,rating,price,winery,ratings_count,region,number_of_flavors,number_of_grapes,grapes,flavors
0,74298,4.5,Beautifully complex champagne. Begins with a y...,2015-07-13T22:05:13.000Z,France,Brut Premier Champagne N.V.,N.V.,4.2,65.098163,Louis Roederer,52143,Champagne Premier Cru,13,3,"['Chardonnay', 'Pinot Noir', 'Pinot Meunier']","{'tree_fruit': '2161', 'non_oak': '1909', 'cit..."
1,74298,4.5,"Its a Non Vintage, but drinking old as cellare...",2021-06-19T03:38:24.000Z,France,Brut Premier Champagne N.V.,N.V.,4.2,65.098163,Louis Roederer,52143,Champagne Premier Cru,13,3,"['Chardonnay', 'Pinot Noir', 'Pinot Meunier']","{'tree_fruit': '2161', 'non_oak': '1909', 'cit..."
2,74298,4.5,"In between the Italian wine reviews, it was ti...",2016-10-20T18:45:18.000Z,France,Brut Premier Champagne N.V.,N.V.,4.2,65.098163,Louis Roederer,52143,Champagne Premier Cru,13,3,"['Chardonnay', 'Pinot Noir', 'Pinot Meunier']","{'tree_fruit': '2161', 'non_oak': '1909', 'cit..."
3,74298,4.5,"Ripe open toasty, powerfull, Smells less compl...",2017-06-06T10:03:49.000Z,France,Brut Premier Champagne N.V.,N.V.,4.2,65.098163,Louis Roederer,52143,Champagne Premier Cru,13,3,"['Chardonnay', 'Pinot Noir', 'Pinot Meunier']","{'tree_fruit': '2161', 'non_oak': '1909', 'cit..."
4,74298,4.5,This is a lovely NV Champagne at this price le...,2018-03-18T13:43:44.000Z,France,Brut Premier Champagne N.V.,N.V.,4.2,65.098163,Louis Roederer,52143,Champagne Premier Cru,13,3,"['Chardonnay', 'Pinot Noir', 'Pinot Meunier']","{'tree_fruit': '2161', 'non_oak': '1909', 'cit..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351761,1208798,3.0,"Dry, slight oak. Crisp. Great French chard for...",2016-10-19T21:05:57.000Z,France,Vosne-Romanée 2017,2017,4.3,91.500000,Albert Bichot,48,Vosne-Romanée,11,1,['Pinot Noir'],"{'red_fruit': '28', 'earth': '20', 'oak': '16'..."
351762,1208798,4.0,"Superb, with a long life ahead of it. Well, no...",2014-08-18T16:33:43.000Z,France,Vosne-Romanée 2017,2017,4.3,91.500000,Albert Bichot,48,Vosne-Romanée,11,1,['Pinot Noir'],"{'red_fruit': '28', 'earth': '20', 'oak': '16'..."
351763,1208798,4.5,A bit heavy but very good after 6y,2020-10-09T18:42:04.000Z,France,Vosne-Romanée 2017,2017,4.3,91.500000,Albert Bichot,48,Vosne-Romanée,11,1,['Pinot Noir'],"{'red_fruit': '28', 'earth': '20', 'oak': '16'..."
351764,1208798,5.0,"Very fruity, Elegant, expressive and Hint of O...",2020-03-19T19:13:30.000Z,France,Vosne-Romanée 2017,2017,4.3,91.500000,Albert Bichot,48,Vosne-Romanée,11,1,['Pinot Noir'],"{'red_fruit': '28', 'earth': '20', 'oak': '16'..."
351765,1208798,4.5,"Lighter, very well balanced, taste of terroir-...",2016-04-11T11:01:18.000Z,France,Vosne-Romanée 2017,2017,4.3,91.500000,Albert Bichot,48,Vosne-Romanée,11,1,['Pinot Noir'],"{'red_fruit': '28', 'earth': '20', 'oak': '16'..."

### Clean Country Data

In [22]:
df3 = pd.read_csv("asset/country.csv")
df3

,country_code,country,native_name,seo_name,regions_count,users_count,wines_count,wineries_count,most_used_grapes,currency_code,currency_name,currency_prefix,currency_suffix
0,af,Afghanistan,افغانستان,afghanistan,0,6400,195,95,"[{'id': 2, 'name': 'Cabernet Sauvignon', 'seo_...",USD,US Dollars,$,NaN
1,al,Albania,Shqipëria,albania,41,44936,403,74,"[{'id': 10, 'name': 'Merlot', 'seo_name': 'mer...",USD,US Dollars,$,NaN
2,dz,Algeria,الجزائر,algeria,7,4391,126,9,"[{'id': 75, 'name': 'Cinsault', 'seo_name': 'c...",USD,US Dollars,$,NaN
3,as,American Samoa,Amerika Sāmoa,american-samoa,0,3575,0,0,[],USD,US Dollars,$,NaN
4,ad,Andorra,Andorra,andorra,0,9935,18,6,"[{'id': 14, 'name': 'Pinot Noir', 'seo_name': ...",EUR,Euros,€,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
248,we,Westeros,Westeros,westeros,11,3366,19,3,"[{'id': 15, 'name': 'Riesling', 'seo_name': 'r...",EUR,Euros,€,NaN
249,ye,Yemen,اليمن,yemen,0,436,0,0,[],USD,US Dollars,$,NaN
250,zm,Zambia,Zambia,zambia,0,2344,9,2,"[{'id': 17, 'name': 'Sauvignon Blanc', 'seo_na...",USD,US Dollars,$,NaN
251,zw,Zimbabwe,Zimbabwe,zimbabwe,0,2878,23,2,"[{'id': 10, 'name': 'Merlot', 'seo_name': 'mer...",USD,US Dollars,$,NaN
252,ax,Åland Islands,Åland,aland-islands,0,2301,0,0,[],USD,US Dollars,$,NaN

In [23]:
grapes = df3['most_used_grapes'].apply(lambda x: re.findall('{(.*?)}', x))
split_grapes = pd.DataFrame(grapes.tolist(), columns=['grape_1', 'grape_2', 'grape_3'])
split_grapes.fillna(value='no values', inplace=True)


split_grapes['grape_1_id'] = split_grapes['grape_1'].apply(lambda x: re.findall('id\W*(.*?)\W', x))
split_grapes['grape_1_id'] = split_grapes['grape_1_id'].apply(lambda x: x[0] if len(x) > 0 else None)

split_grapes['grape_1_name'] = split_grapes['grape_1'].apply(lambda x: re.findall('\'name\W*(.*?)\W', x))
split_grapes['grape_1_name'] = split_grapes['grape_1_name'].apply(lambda x: x[0] if len(x) > 0 else None)

split_grapes['grape_2_id'] = split_grapes['grape_2'].apply(lambda x: re.findall('id\W*(.*?)\W', x))
split_grapes['grape_2_id'] = split_grapes['grape_2_id'].apply(lambda x: x[0] if len(x) > 0 else None)

split_grapes['grape_2_name'] = split_grapes['grape_2'].apply(lambda x: re.findall('\'name\W*(.*?)\W', x))
split_grapes['grape_2_name'] = split_grapes['grape_2_name'].apply(lambda x: x[0] if len(x) > 0 else None)

split_grapes['grape_3_id'] = split_grapes['grape_3'].apply(lambda x: re.findall('id\W*(.*?)\W', x))
split_grapes['grape_3_id'] = split_grapes['grape_3_id'].apply(lambda x: x[0] if len(x) > 0 else None)

split_grapes['grape_3_name'] = split_grapes['grape_3'].apply(lambda x: re.findall('\'name\W*(.*?)\W', x))
split_grapes['grape_3_name'] = split_grapes['grape_3_name'].apply(lambda x: x[0] if len(x) > 0 else None)

split_grapes.drop(['grape_1', 'grape_2', 'grape_3'], axis=1, inplace=True)

split_grapes

    grape_1_id grape_1_name grape_2_id grape_2_name grape_3_id    grape_3_name
0            2     Cabernet         10       Merlot          1          Shiraz
1           10       Merlot          2     Cabernet          5      Chardonnay
2           75     Cinsault          8     Grenache         40        Alicante
3         None         None       None         None       None            None
4           14        Pinot          5   Chardonnay          7  Gewürztraminer
..         ...          ...        ...          ...        ...             ...
248         15     Riesling          2     Cabernet          5      Chardonnay
249       None         None       None         None       None            None
250         17    Sauvignon          2     Cabernet         10          Merlot
251         10       Merlot          5   Chardonnay          2        Cabernet
252       None         None       None         None       None            None

[253 rows x 6 columns]

In [24]:
df3 = df3.join(split_grapes)
df3.drop('most_used_grapes', axis=1, inplace=True)
df3

,country_code,country,native_name,seo_name,regions_count,users_count,wines_count,wineries_count,currency_code,currency_name,currency_prefix,currency_suffix,grape_1_id,grape_1_name,grape_2_id,grape_2_name,grape_3_id,grape_3_name
0,af,Afghanistan,افغانستان,afghanistan,0,6400,195,95,USD,US Dollars,$,NaN,2,Cabernet,10,Merlot,1,Shiraz
1,al,Albania,Shqipëria,albania,41,44936,403,74,USD,US Dollars,$,NaN,10,Merlot,2,Cabernet,5,Chardonnay
2,dz,Algeria,الجزائر,algeria,7,4391,126,9,USD,US Dollars,$,NaN,75,Cinsault,8,Grenache,40,Alicante
3,as,American Samoa,Amerika Sāmoa,american-samoa,0,3575,0,0,USD,US Dollars,$,NaN,None,None,None,None,None,None
4,ad,Andorra,Andorra,andorra,0,9935,18,6,EUR,Euros,€,NaN,14,Pinot,5,Chardonnay,7,Gewürztraminer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
248,we,Westeros,Westeros,westeros,11,3366,19,3,EUR,Euros,€,NaN,15,Riesling,2,Cabernet,5,Chardonnay
249,ye,Yemen,اليمن,yemen,0,436,0,0,USD,US Dollars,$,NaN,None,None,None,None,None,None
250,zm,Zambia,Zambia,zambia,0,2344,9,2,USD,US Dollars,$,NaN,17,Sauvignon,2,Cabernet,10,Merlot
251,zw,Zimbabwe,Zimbabwe,zimbabwe,0,2878,23,2,USD,US Dollars,$,NaN,10,Merlot,5,Chardonnay,2,Cabernet
252,ax,Åland Islands,Åland,aland-islands,0,2301,0,0,USD,US Dollars,$,NaN,None,None,None,None,None,None